### ISSUE TITLE
Finding the right cert

### ISSUE THREAD

**Issue by onovotny** [glennawatson/GitSMimeSign#23]
The user matching function doesn't appear to check the EKU of the cert to make sure it's good for signing:

https://github.com/glennawatson/GitSMimeSign/blob/master/src/GITSMimeSign/Helpers/CertificateHelper.cs#L50

Probably best to check the EKU list for Secure Email (1.3.6.1.5.5.7.3.4)

**Comment by glennawatson** [comment]
The check was added for both `--list-keys` and the signing portion as part of version 1.4.1
