### ISSUE TITLE
Tool doesn't work if .NET Core 3.1 is not present

### ISSUE THREAD

**Issue by clairernovotny** [glennawatson/GitSMimeSign#94]
.NET 3.1 is getting old... some machines only have .NET 5 and .NET 6. Can you please release a version that multi-targets to .NET 6 and/or sets the runtime fallback to include a major version?

Basically, add this file to your project:

https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/src/nbgv/runtimeconfig.template.json

Then it'll roll forward if a 3.1 runtime isn't present.

**Comment by glennawatson** [comment]
I'll remove netcoreapp3.1 as a target once .net 6 is fully out since that's the new LTS. At the moment just multi target netcoreapp3.1/net5/net6
